Repository qlghwp123/Plan-T, pull requests merged in 2022-12, with the labels that each got.

#48 templates: accounts_form.html 수정
  templates/accounts/complete/accounts_form.html
Labels: FE

#50 templates: today_main.html 수정
  templates/todos/complete/today_main.html
  todos/views.py
Labels: FE

#51 fix : todos/model
  todos/models.py
Labels: BE, fix, test

#52 templates: today_main.html 재수정
  templates/todos/complete/today_main.html
Labels: FE, fix, test

#53 templates : time picker input js 코드 작성
  templates/todos/working/create_today.html
Labels: FE, test, JS

#54 templates: today_main.html - js 현재 날짜 추가
  static/script/script.js
  static/styles/today.css
  templates/todos/complete/today_main.html
Labels: FE, fix, JS

#55 feature : todos/week
  templates/todos/working/week_todos.html
  todos/views.py
Labels: feature, BE

#56 feature : todos/create 타임테이블 시간저장 확인로직 추가
  todos/forms.py
  todos/tests.py
  todos/views.py
Labels: feature, BE

#58 templates: week_todos.html 생성 + js
  static/script/script.js
  static/styles/main.css
  static/styles/today.css
  templates/base.html
  templates/todos/complete/today_main.html
  templates/todos/working/week_todos.html
Labels: FE, JS

#59 fix : todos/create refactor todos/today todos/week
  todos/views.py
Labels: feature, BE, fix, refactor

#61 style : todos/create/time/annotation
  todos/views.py
Labels: BE, style

#63 feature : url todos/week/few_week
  todos/urls.py
  todos/views.py
Labels: feature, BE

#65 fix : todos/time
  templates/todos/complete/today_main.html
  todos/views.py
Labels: BE, fix

#66 templates: today_main.html, week_todos.html 수정중
  accounts/views.py
  static/script/script.js
  templates/accounts/complete/accounts_form.html
  templates/base.html
  templates/todos/complete/today_main.html
  templates/todos/working/week_todos.html
Labels: FE, fix, JS

#67 fix : fix/todos/re
  todos/views.py
Labels: BE, fix

#68 templates: today_main.html 중복 수정
  templates/base.html
  templates/todos/complete/today_main.html
Labels: FE, fix

#69 fix : todos/create
  todos/views.py
Labels: BE, fix

#70 templates: today_main.html 재수정
  templates/todos/complete/today_main.html
Labels: FE

#71 fix : todos/today/create
  accounts/views.py
  todos/function.py
  todos/views.py
Labels: BE, fix

#72 templates: today_main js이벤트 수정중
  static/script/script.js
  static/styles/today.css
  templates/todos/complete/today_main.html
  templates/todos/working/week_todos.html
Labels: FE, JS

#73 templates : study-task toggle js 코드 작성
  static/styles/create_today.css
  static/styles/today.css
  templates/todos/working/today.html
Labels: FE, JS

#74 feature : todos/read_all/past/present/future
  todos/views.py
Labels: feature, BE

#75 Test/study/list
  templates/todos/test/study_list.html
  templates/todos/test/test_create.html
  todos/urls.py
  todos/views.py
Labels: BE, test

#76 templates : INPUT FILE NAME 표시 JS 코드 작성
  static/styles/create_today.css
  templates/todos/working/create_today.html
Labels: FE, JS

#77 templates : FILE INPUT alltask.html script, css 수정
  static/styles/create_today.css
  templates/todos/working/alltask.html
Labels: FE, JS

#83 feature : social_login google
  pjt/settings.py
  pjt/urls.py
  requirements.txt
  templates/main_index.html
  templates/todos/test/study_list.html
Labels: docs, feature, BE

#84 templates: week_todos.html Btn 수정중
  static/script/script.js
  templates/todos/working/week_todos.html
  todos/urls.py
  todos/views.py
Labels: FE, JS

#85 feature : today/update 정보를 비동기로 보내줄 수 있게 구현
  todos/views.py
Labels: feature, BE

#87 fix : todos/today/week
  templates/todos/complete/today_main.html
  templates/todos/working/week_todos.html
  todos/function.py
  todos/urls.py
  todos/views.py
Labels: BE, fix

#88 feature : study 앱 생성 및 study 모델 구현
  pjt/settings.py
  pjt/urls.py
  studies/__init__.py
  studies/admin.py
  studies/apps.py
  studies/models.py
  studies/tests.py
  studies/urls.py
  studies/views.py
  templates/studies/test/index.html
Labels: feature, BE

#89 feature : study 모델링 완료
  studies/models.py
Labels: feature, BE

#91 feature : study/todo
  studies/forms.py
  studies/models.py
  studies/urls.py
  studies/views.py
  templates/studies/test/todos_create.html
  templates/todos/working/week.html
Labels: feature, BE

#94 feature : todos/read_all
  requirements.txt
  todos/views.py
Labels: feature, BE

#98 refactor : study 모델 수정
  studies/models.py
Labels: BE, refactor

#99 test : study/join/accept 테스트
  accounts/models.py
  studies/models.py
  studies/urls.py
  studies/views.py
Labels: BE, test

#100 templates: week_todos.html 비동기 연결 완성
  static/script/script.js
  templates/todos/working/week_todos.html
Labels: FE, JS

#101 templates : 토글 JS 수정, study_index.html 화면 구성
  static/styles/alltask.css
  static/styles/create_today.css
  static/styles/study_index.css
  static/styles/today.css
  templates/studies/working/study_index.html
  templates/todos/complete/today_main.html
  templates/todos/working/alltask.html
  templates/todos/working/create_today.html
Labels: FE, refactor, JS

#102 feature : studies/detail
  studies/urls.py
  studies/views.py
  templates/studies/test/detail.html
  templates/studies/test/index.html
Labels: feature, BE

#103 fix : fix/todos/today/week 0 제거
  templates/todos/complete/today_main.html
Labels: FE, fix

#104 fix : Update url in base.html
  templates/base.html
Labels: FE, fix

#106 feature : studies/accept max값 제한하는 코드
  studies/views.py
Labels: feature, BE

#107 style : todos/today/timetable
  todos/views.py
Labels: BE, style

#108 feature : studies/index 카테고리 받을 준비
  studies/views.py
Labels: feature, BE

#109 templates : study_index.html 수정
  static/styles/main.css
  static/styles/study_index.css
  templates/studies/working/study_index.html
Labels: FE

#111 templates: today_main.html 할일 상세 폼 수정 - 세부 조정 필요
  static/script/script.js
  static/styles/create_today.css
  static/styles/main.css
  static/styles/today.css
  templates/todos/complete/today_main.html
  todos/views.py
Labels: FE, JS

#112 templates: today_main.html 구조 수정
  templates/todos/complete/today_main.html
Labels: FE, fix

#114 docs : Add comments
  accounts/views.py
  static/script/script.js
  studies/views.py
Labels: docs, BE

#115 templates : create_study.html 구조 템플릿
  static/styles/create_study.css
  static/styles/create_today.css
  static/styles/study_detail.css
  static/styles/study_index.css
  templates/studies/working/create_study.html
  templates/studies/working/study_detail.html
  templates/studies/working/study_index.html
Labels: FE

#116 style : study/todos 방장만 만들수 있게끔
  studies/views.py
  templates/studies/test/detail.html
  templates/studies/test/index.html
Labels: BE, style

#118 refactor : Add class statement
  static/script/script.js
  templates/todos/working/week_todos.html
Labels: FE, refactor, JS

#119 fix : Add statement adding owner to participated
  studies/views.py
  templates/studies/test/detail.html
Labels: FE, BE, fix, refactor

#121 feature : studies/index/create 기능 연결
  studies/models.py
  studies/urls.py
  studies/views.py
  templates/studies/working/create_study.html
  templates/studies/working/study_index.html
  todos/views.py
Labels: feature, BE

#123 templates : study_update.html 구조 템플릿
  static/styles/create_today.css
  static/styles/study.css
  templates/studies/working/create_study.html
  templates/studies/working/study_info.html
  templates/studies/working/study_update.html
Labels: FE

#124 fix : tag 모델 수정
  todos/models.py
  todos/tests.py
  todos/views.py
Labels: BE, fix

#125 templates: today_main.html 타임테이블 생성, 세부 정리
  static/script/script.js
  static/styles/create_today.css
  static/styles/today.css
  templates/todos/complete/today_main.html
Labels: FE, JS

#126 Fix/studies/create
  studies/models.py
  studies/urls.py
  studies/views.py
  templates/studies/working/create_study.html
  templates/studies/working/study_index.html
  templates/studies/working/study_info.html
Labels: feature, BE, fix

#127 feature : todos/today/achievement
  todos/views.py
Labels: feature, BE

#128 style : todos/today/achievenent
  todos/views.py
Labels: BE, style

#129 templates: today_main.html 세부수정, week_todos js 수정
  static/script/script.js
  static/styles/main.css
  static/styles/today.css
  templates/todos/complete/today_main.html
  templates/todos/working/week_todos.html
  todos/views.py
Labels: FE, JS

#130 fix : 태그 저장 안되던 오류 수정
  accounts/tests.py
  accounts/views.py
  function.py
  pjt/settings.py
  requirements.txt
  templates/accounts/working/mypage.html
  todos/tests.py
  todos/views.py
Labels: BE, fix

#131 fix : 태그 create, update 버그 수정 // 태그 클라우드 구현
  accounts/urls.py
  accounts/views.py
  pjt/views.py
  templates/accounts/working/login.html
  templates/accounts/working/mypage.html
  templates/accounts/working/same_tag.html
  todos/models.py
  todos/tests.py
  todos/views.py
Labels: feature, BE, fix

#132 feature : study/member_number
  studies/models.py
  studies/views.py
  todos/views.py
Labels: feature, BE

#133 fix : 로그인 템플릿 연결
  templates/accounts/working/login.html
Labels: BE, fix

#137 templates : studies App 수정
  static/styles/create_today.css
  studies/views.py
  templates/studies/complete/create_study.html
  templates/studies/complete/study_detail.html
  templates/studies/complete/study_index.html
  templates/studies/complete/study_info.html
  templates/studies/complete/study_update.html
  templates/studies/working/study_index.html
  templates/studies/working/study_info.html
Labels: FE, fix, style

#138 Templates/today upate
  static/script/script.js
  static/styles/create_today.css
  templates/base.html
  templates/todos/complete/today_main.html
  templates/todos/complete/week_todos.html
  todos/views.py
Labels: FE, JS

#139 templates: today todo 수정 비동기, today_readAll 연결
  static/script/script.js
  static/styles/alltask.css
  static/styles/main.css
  static/styles/today.css
  templates/base.html
  templates/todos/complete/all_todos.html
  templates/todos/complete/today_main.html
  todos/views.py
Labels: FE, JS

#141 templates : todos alltask.html working 파일 토글 JS 수정
  static/styles/alltask.css
  static/styles/study_form.css
  templates/studies/working/study_detail.html
  templates/todos/working/alltask.html
Labels: FE, refactor, JS

#142 feature : studies/detail 기능 연결
  studies/urls.py
  studies/views.py
  templates/studies/complete/study_detail.html
  templates/studies/complete/study_index.html
Labels: feature, BE

#143 Chat/init
  chat/__init__.py
  chat/admin.py
  chat/apps.py
  chat/consumers.py
  chat/models.py
  chat/routing.py
  chat/templates/chat/index.html
  chat/templates/chat/room.html
  chat/tests.py
  chat/urls.py
  chat/views.py
  pjt/asgi.py
  pjt/routing.py
  pjt/settings.py
  pjt/urls.py
  requirements.txt
  todos/views.py
Labels: docs, BE, fix

#144 templates: today_main.html 삭제 비동기 추가
  static/script/script.js
  templates/todos/complete/today_main.html
  todos/views.py
Labels: FE, JS

#146 fix : Update chat/room
  chat/views.py
Labels: BE, fix

#147 fix : Update room.html
  chat/templates/chat/room.html
Labels: FE, fix

#148 fix : Delete mistake in Line feed check condition
  chat/templates/chat/room.html
Labels: FE, fix, JS

#149 fix : Update variable in room.html
  chat/templates/chat/room.html
Labels: FE, fix, JS

#150 templates : study_index.html 탭 이동 JS 코드 작성
  static/styles/alltask.css
  templates/base.html
  templates/studies/complete/study_index.html
Labels: FE, JS

#151 templates : study_index.html 화면 깨짐 오류 해결
  pjt/settings.py
  templates/main_index.html
  templates/studies/complete/study_index.html
  templates/studies/working/study_index.html
Labels: FE, fix

#152 templates: today_main.html 타임테이블 시간 표시 수정
  pjt/settings.py
  static/script/script.js
Labels: FE, JS

#153 templates : study_info.html category 라디오 버튼 check 표시 JS 작성
  templates/accounts/complete/accounts_form.html
  templates/studies/complete/study_info.html
Labels: FE, JS

#155 feature : todos/today/studieslist
  templates/todos/complete/today_main.html
  todos/views.py
Labels: feature, BE

#156 feature : studies/update 기능 연결
  studies/urls.py
  studies/views.py
  templates/studies/complete/create_study.html
  templates/studies/complete/study_detail.html
  templates/studies/complete/study_update.html
  templates/todos/complete/today_main.html
Labels: feature, BE

#157 fix : studies/update/category
  templates/studies/complete/study_update.html
Labels: BE, fix

#158 Refactor/decorator
  accounts/decorator.py
  accounts/views.py
  chat/views.py
  studies/views.py
  templates/accounts/complete/.gitkeep
  templates/todos/complete/.gitkeep
  templates/todos/complete/all_todos.html
  templates/todos/working/.gitkeep
  todos/views.py
Labels: feature, BE, refactor

#159 templates : studies App 수정
  static/styles/create_today.css
  static/styles/main.css
  static/styles/study_detail.css
  static/styles/study_form.css
  static/styles/study_index.css
  templates/studies/complete/study_detail.html
  templates/studies/complete/study_info.html
  templates/studies/complete/study_update.html
Labels: FE, fix, JS

#160 fix : Update decorator in code
  accounts/views.py
  studies/views.py
  todos/views.py
Labels: BE, fix

#161 fix : Update typo
  accounts/views.py
Labels: BE, fix

#162 templates : studies app 수정
  static/styles/create_today.css
  static/styles/study_detail.css
  static/styles/study_form.css
  static/styles/study_index.css
  templates/studies/complete/create_study.html
  templates/studies/complete/study_detail.html
  templates/studies/complete/study_update.html
Labels: FE, style

#163 templates: today_main tag 포함 출력, 수정
  static/script/script.js
  static/styles/create_today.css
  static/styles/main.css
  static/styles/today.css
  templates/todos/complete/today_main.html
  todos/views.py
Labels: FE, JS

#164 templates: today_main.html 할일 삭제 비동기 완료
  static/script/script.js
  templates/todos/complete/today_main.html
Labels: FE, JS

#165 templates: main_index 슬라이드 추가
  static/script/script.js
  static/styles/accounts.css
  static/styles/main.css
  templates/main_index.html
Labels: FE, JS

#166 feature : studies/todos/management
  studies/models.py
  studies/urls.py
  studies/views.py
  templates/studies/complete/study_detail.html
Labels: feature, BE

#167 templates : mediaquery.css 파일 추가, 수정
  static/styles/main.css
  static/styles/mediaquery.css
  static/styles/study_index.css
  templates/base.html
  templates/studies/complete/study_index.html
Labels: FE, style

#168 Studies/search
  studies/views.py
  templates/studies/complete/study_index.html
Labels: feature, BE

#170 Templates/accounts
  accounts/forms.py
  accounts/views.py
  static/styles/accounts.css
  templates/accounts/complete/login.html
  templates/accounts/working/accounts_update.html
  templates/accounts/working/login.html
  templates/accounts/working/main_login.html
  templates/accounts/working/mypage.html
  templates/accounts/working/same_tag.html
  templates/main_index.html
Labels: FE

#171 fix : todos/week 다른 유저 보이는 현상
  todos/views.py
Labels: BE, fix

#172 fix : studies/detail
  studies/views.py
Labels: BE, fix

#173 templates : studies pagination 구현, 반응형 수정
  static/styles/mediaquery.css
  static/styles/study_detail.css
  static/styles/study_form.css
  static/styles/study_index.css
  studies/views.py
  templates/studies/complete/study_detail.html
  templates/studies/complete/study_index.html
  templates/studies/complete/study_info.html
Labels: FE

#174 fix : studies/index 가입&진입하기, 생활 클릭 안되는 문제
  templates/studies/complete/study_index.html
Labels: FE, fix

#175 fix : studies/index/views/paginator/search
  studies/views.py
Labels: BE, fix

#176 feature : studies/info 가입 비동기
  studies/views.py
  templates/studies/complete/study_info.html
Labels: feature, FE, BE, fix

#177 feature : studies/detail delete&탈퇴&사진 info 가입제한
  studies/urls.py
  studies/views.py
  templates/studies/complete/study_detail.html
  templates/studies/complete/study_info.html
Labels: feature, FE, BE, fix

#180 fix : todos/forms 이미지 제거
  todos/forms.py
Labels: BE, fix

#181 feature : studies/create 시작일 종료일 html
  templates/base.html
  templates/studies/complete/create_study.html
  templates/studies/complete/study_info.html
Labels: feature, FE

#183 templates : 반응형 화면 디자인
  static/script/script.js
  static/styles/mediaquery.css
  static/styles/study_detail.css
  static/styles/today.css
  templates/studies/complete/study_detail.html
  templates/todos/complete/today_main.html
  templates/todos/complete/week_todos.html
Labels: FE, style, JS

#184 fix : study/todo 기간 올바르게 저장되도록 코드수정
  studies/views.py
  templates/studies/working/study_detail.html
  todos/views.py
Labels: bug, BE, fix

#186 fix : Update nickname part
  chat/templates/chat/room.html
Labels: FE, JS

#187 Templates/account fix
  accounts/views.py
  static/styles/accounts.css
  static/styles/today.css
  templates/accounts/working/mypage.html
  templates/todos/complete/all_todos.html
  templates/todos/complete/today_main.html
  templates/todos/complete/week_todos.html
  templates/todos/working/alltask.html
Labels: FE

#188 fix : todos/tags
  todos/views.py
Labels: BE, fix

#189 Fix/typo
  accounts/models.py
  chat/templates/chat/room.html
Labels: FE, BE, fix, JS

#190 fix : studies/index/catagory
  templates/studies/complete/study_index.html
Labels: BE, fix

#191 fix : Update pagination url
  templates/studies/complete/study_index.html
Labels: FE, fix, JS

#192 feature : studies/create/maxlength
  templates/studies/complete/create_study.html
Labels: feature, FE

#193 Fix/study index.html
  templates/studies/complete/study_index.html
Labels: feature, FE, fix, style, JS

#194 fix : accounts update form 이미지 받아오는 문제 해결
  accounts/forms.py
  accounts/views.py
  static/styles/study_form.css
  templates/base.html
  templates/studies/complete/study_detail.html
Labels: bug, BE, fix

#195 fix : studies/index
  studies/views.py
  templates/studies/complete/study_index.html
Labels: FE, BE, fix

#196 fix : todos/today/update/tag
  todos/views.py
Labels: BE, fix

#197 style : Update category url
  templates/studies/complete/study_index.html
Labels: FE, style, JS

#198 fix : studies/views/accept_and_drive_out 수락 신청
  studies/views.py
Labels: BE, fix

#201 feature : studies/ 탈퇴,강퇴시 해당 스터디 todos 삭제
  studies/views.py
Labels: feature, BE

#202 Templates/timetalbe fix
  static/script/script.js
  static/styles/today.css
Labels: FE, fix, JS

#203 feature : studies/index 자리가 없어요 추가
  templates/studies/complete/study_index.html
Labels: feature, FE

#204 feature : 프로필 페이지 todo 달성률 데이터 넘겨줌
  accounts/views.py
Labels: feature, BE

#205 templates: mypage.html 사진 위치, 이미지 크기 조정
  static/styles/accounts.css
  static/styles/mediaquery.css
  templates/accounts/working/mypage.html
  templates/base.html
  templates/todos/complete/today_main.html
Labels: FE

#206 templates : study_index.html pagination a태그 padding 추가
  static/styles/study_index.css
Labels: FE, style

#207 fix : Update user model and user update html
  accounts/models.py
  templates/accounts/working/accounts_update.html
Labels: bug, FE, BE, fix, JS

#209 style : 코드 짧게 수정
  accounts/views.py
  todos/views.py
Labels: BE, style

#210 feature : studies/new_member add study_todos
  studies/views.py
  templates/studies/complete/study_detail.html
Labels: feature, BE

#211 templates: datepicker script.js로 코드 수정, 이동
  static/script/script.js
  static/styles/mediaquery.css
  templates/studies/complete/create_study.html
  templates/studies/complete/study_detail.html
Labels: FE, JS

#212 templates : study_index 부분 화면상단버튼 생성, JS 코드 작성
  static/styles/mediaquery.css
  static/styles/study_form.css
  static/styles/study_index.css
  templates/studies/complete/study_index.html
Labels: FE, JS

#213 style : 스터디 인덱스 페이지 순서정렬 바꿈
  studies/views.py
Labels: BE, style

#214 templates: 프로필-태그 상세 클릭 시 템플릿, main 퍼센트 수정
  static/script/mk_charts.js
  static/script/script.js
  static/styles/accounts.css
  static/styles/main.css
  static/styles/mk_charts.css
  templates/accounts/working/mypage.html
  templates/accounts/working/same_tag.html
  templates/base.html
  templates/todos/complete/all_todos.html
  templates/todos/complete/today_main.html
Labels: FE, fix, JS

#215 style : 스터디 인덱스 페이지 순서정렬 바꿈
  studies/views.py
Labels: BE, style

#216 fix : Update admin.py to access admin page
  .gitignore
  todos/admin.py
Labels: BE, fix

#217 Refactor/chat
  chat/templates/chat/index.html
  chat/templates/chat/room.html
  chat/urls.py
  chat/views.py
  templates/studies/complete/create_study.html
  templates/studies/complete/study_detail.html
  templates/todos/complete/today_main.html
Labels: FE, fix, style

#218 feature : studies/detail과info POST 비동기
  studies/views.py
  templates/studies/complete/study_detail.html
  templates/studies/complete/study_info.html
Labels: feature, FE, BE, fix

#219 templates : base.html message 알림창 생성
  static/styles/main.css
  static/styles/mediaquery.css
  static/styles/study_detail.css
  studies/views.py
  templates/base.html
  templates/main_index.html
  templates/studies/complete/study_detail.html
  todos/views.py
Labels: FE

#222 fix : Update read_all func
  templates/todos/complete/all_todos.html
  todos/admin.py
  todos/urls.py
  todos/views.py
Labels: feature, FE, BE, fix, JS

#223 fix : Update typo and Add TodosAdmin
  todos/admin.py
Labels: BE, fix

#224 fix : Add fields in TodosAdmin
  todos/admin.py
Labels: BE, fix

#225 style : Add blank line
  todos/admin.py
Labels: BE, fix, style

#226 test : Change import sequence
  todos/admin.py
Labels: bug, BE, test

#229 templates : chat.html 구조 템플릿 작성
  chat/templates/chat/test.html
  chat/views.py
  static/styles/chat.css
  templates/base.html
Labels: FE

#230 fix : studies/views/again 안보내진거 다시
  studies/views.py
Labels: feature, BE

#231 fix : studies/detail/수락 버튼
  studies/views.py
  templates/studies/complete/study_detail.html
Labels: feature, FE, BE, fix

#232 fix : studies/create 잘못입력시 메시지 추가
  studies/views.py
Labels: BE, fix

#233 fix : studies/create/button 최소 버튼 url 추가
  templates/studies/complete/create_study.html
Labels: FE, fix

#234 templates : study_detail.html 스터디 승인 토글 수정
  static/styles/mediaquery.css
  static/styles/study_detail.css
  static/styles/study_form.css
  templates/studies/complete/create_study.html
  templates/studies/complete/study_detail.html
  templates/studies/complete/study_index.html
  templates/studies/complete/study_update.html
Labels: FE, JS

#235 fix : studies/update 수정 반장만 보이게, 메시지 추가
  studies/views.py
  templates/studies/complete/study_detail.html
Labels: feature, FE, BE, fix

#238 Fix/chat
  chat/templates/chat/room.html
  chat/templates/chat/test.html
  chat/views.py
  templates/studies/complete/study_detail.html
Labels: FE, BE, fix, test, JS

#239 fix : todos/tag 띄여쓰기 제거
  studies/views.py
  todos/views.py
Labels: BE, fix

#240 templates : study_detail.html 토글 JS 문제 해결, 코드 수정
  static/styles/study_form.css
  templates/studies/complete/study_detail.html
Labels: FE, JS
