Repository qlghwp123/Plan-T, pull requests merged in 2022-11, with the labels that each got.

#3 templates : static init.css 추가
  pjt/settings.py
  static/styles/init.css
Labels: FE

#4 feature : Add accounts/model
  accounts/models.py
  pjt/settings.py
Labels: feature, BE

#9 templates: main.css 생성
  static/styles/fontall.css
  static/styles/main.css
  static/styles/webfont/NanumSquareNeoTTF-bRg.eot
  static/styles/webfont/NanumSquareNeoTTF-bRg.woff
  static/styles/webfont/NanumSquareNeoTTF-bRg.woff2
  static/styles/webfont/NanumSquareNeoTTF-cBd.eot
  static/styles/webfont/NanumSquareNeoTTF-cBd.woff
  static/styles/webfont/NanumSquareNeoTTF-cBd.woff2
Labels: FE

#11 feature : settings/urls
  accounts/urls.py
  pjt/settings.py
  pjt/urls.py
  templates/todos/working/index.html
  todos/urls.py
  todos/views.py
Labels: feature, BE

#12 docs : docs/requirements.txt
  requirements.txt
Labels: docs, BE

#13 feature : todos/today, todos/forms
  templates/todos/working/index.html
  todos/forms.py
  todos/urls.py
  todos/views.py
Labels: feature, BE

#14 templates: main.css 수정
  static/img/planT_logo.svg
  static/styles/main.css
  templates/base.html
Labels: FE

#15 feature : Add accounts/signup func
  accounts/forms.py
  accounts/models.py
  accounts/templates/test/signup.html
  accounts/urls.py
  accounts/views.py
Labels: feature, BE, test

#17 feature : Add accounts/login func
  accounts/templates/test/form.html
  accounts/templates/test/main.html
  accounts/urls.py
  accounts/views.py
Labels: feature, BE, test

#18 feature : Add accounts/logout func
  accounts/templates/test/main.html
  accounts/urls.py
  accounts/views.py
Labels: feature, BE, test

#19 feature : todos/week
  templates/todos/working/week.html
  todos/urls.py
  todos/views.py
Labels: feature, BE

#20 templates : create_today.html 템플릿 생성, 수정
  static/styles/create_today.css
  templates/todos/working/create_today.html
Labels: FE

#21 feature : todos/create
  todos/urls.py
  todos/views.py
Labels: feature, BE

#22 feature : 타임테이블 생성기능 추가
  templates/todos/working/timetable.html
  todos/forms.py
  todos/urls.py
  todos/views.py
Labels: feature, BE, test

#23 feature : Add accounts/delete func
  accounts/templates/test/main.html
  accounts/urls.py
  accounts/views.py
Labels: feature, BE, test

#24 templates: today.html, today.css 생성
  static/styles/main.css
  static/styles/today.css
  templates/base.html
  templates/todos/working/today.html
Labels: FE

#25 feature : todos/delete(views)
  todos/urls.py
  todos/views.py
Labels: feature, BE

#26 style : todos/today
  todos/views.py
Labels: BE, style

#27 feature : 타임테이블 기능 수정
  templates/todos/working/timetable.html
  todos/urls.py
  todos/views.py
Labels: feature, BE, fix

#28 templates: accounts 템플릿, script.js 생성, favicon 연결
  static/img/planT_logo.svg
  static/script/script.js
  static/styles/accounts.css
  static/styles/favicon/android-chrome-192x192.png
  static/styles/favicon/android-chrome-512x512.png
  static/styles/favicon/apple-touch-icon.png
  static/styles/favicon/favicon-16x16.png
  static/styles/favicon/favicon-32x32.png
  static/styles/favicon/favicon.ico
  static/styles/favicon/site.webmanifest
  static/styles/fontall.css
  static/styles/main.css
  static/styles/today.css
  static/styles/webfont/NanumSquareNeoTTF-dEb.eot
  static/styles/webfont/NanumSquareNeoTTF-dEb.woff
  static/styles/webfont/NanumSquareNeoTTF-dEb.woff2
  templates/accounts/working/main_login.html
  templates/accounts/working/mypage.html
  templates/accounts/working/signup.html
  templates/base.html
  templates/todos/working/today.html
Labels: FE, JS

#29 feature : todos/read_all
  todos/views.py
Labels: feature, BE

#32 refactor : todos.views.today 보완, Todos 모델 보완
  templates/todos/working/index.html
  templates/todos/working/timetable.html
  todos/forms.py
  todos/models.py
  todos/urls.py
  todos/views.py
Labels: BE, refactor

#33 template : alltask 템플릿 생성, 스타일 주기
  static/img/arrow-forward.svg
  static/styles/alltask.css
  static/styles/create_today.css
  templates/todos/working/alltask.html
  templates/todos/working/create_today.html
Labels: FE

#34 templates: accounts_form.html 생성, 로그인, 가입 기능 연결
  accounts/forms.py
  accounts/views.py
  pjt/urls.py
  pjt/views.py
  static/styles/accounts.css
  templates/accounts/complete/accounts_form.html
  templates/accounts/working/main_login.html
  templates/accounts/working/signup.html
  templates/base.html
  templates/main_index.html
Labels: FE

#35 templates: today_main 템플릿 연결, week_todos.html 수정중
  static/styles/main.css
  static/styles/today.css
  templates/base.html
  templates/todos/complete/today_main.html
  templates/todos/working/week_todos.html
  todos/views.py
Labels: FE

#37 feature : todos/read_all todos/today
  templates/todos/working/read_all.html
  templates/todos/working/test_create.html
  templates/todos/working/today.html
  todos/forms.py
  todos/urls.py
  todos/views.py
Labels: feature, BE

#38 refactor : Delete Timetable model, related stuff
  accounts/models.py
  todos/forms.py
  todos/models.py
  todos/urls.py
  todos/views.py
Labels: BE, refactor

#39 fix : todos/today html timetable
  templates/todos/complete/today_main.html
Labels: BE, fix

#40 Todos/today
  todos/views.py
Labels: BE, refactor

#41 feature : todos/today 10분단위 시간표
  todos/views.py
Labels: feature, BE

#42 Style/todos/today
  todos/views.py
Labels: BE, style

#43 templates: today_main.html 수정
  static/script/script.js
  static/styles/today.css
  templates/base.html
  templates/todos/complete/today_main.html
Labels: FE, JS

#44 templates : create_today 시작시간, 종료시간 input 추가
  static/styles/create_today.css
  templates/base.html
  templates/todos/working/create_today.html
Labels: FE, JS

#45 feature : todos/create start end
  templates/todos/complete/today_main.html
  todos/views.py
Labels: feature, BE

#46 fix : todos/model/today/create
  todos/models.py
  todos/views.py
Labels: BE, fix
